// // import Head from "next/head";
// // import Image from "next/image";
// // import { Inter } from "next/font/google";
// // import styles from "@/styles/Home.module.css";
// // import PostList from "@/components/PostList.js";
// // import PostForm from "@/components/PostForm.js";
// // // import MyCarousel from "@/components/MyCarousel";

// // const inter = Inter({ subsets: ["latin"] });

// // export default function Home() {
// //   return (
// //     <>
// //       <Head>
// //         <title>Volunteer With Pru</title>
// //         <meta name="description" content="Generated by create next app" />
// //         <meta name="viewport" content="width=device-width, initial-scale=1" />
// //         <link rel="icon" href="/favicon.ico" />
// //       </Head>
// //       <main className={`${styles.main} ${inter.className}`}>
// //       <h1> Volunteer With Pru</h1>
// //       {/* <MyCarousel /> */}
// //       <img src="https://www.prudential.com/content/dam/community-engagement/Community-Engagement.jpg" text="Third slide" />
// //       <PostList />
// //       <div className="form-area">
// //             <PostForm />
// //       </div>
      

// //       </main>
// //     </>
// //   );
// // }


// import Head from "next/head";
// import Image from "next/image";
// import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";
// import PostList from "@/components/PostList.js";
// import PostForm from "@/components/PostForm.js";

// const inter = Inter({ subsets: ["latin"] });

// export default function Home() {
//   return (
//     <>
//       <Head>
//         <title>Volunteer With Pru</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className={`${styles.main} ${inter.className}`}>
//         <div className="container">
//           <h1 className="text-center mt-5 mb-4">Volunteer With Pru</h1>

//           {/* Hero Image */}
//           <div className="row mb-4">
//             <div className="col">
//               <img
//                 src="https://www.prudential.com/content/dam/community-engagement/Community-Engagement.jpg"
//                 className="img-fluid rounded shadow-lg"
//                 alt="Community Engagement"
//               />
//             </div>
//           </div>

//           {/* Post List */}
//           <div className="row">
//             <div className="col-lg-8">
//               <PostList />
//             </div>

//             {/* Post Form */}
//             <div className="col-lg-4">
//               <div className="card shadow-sm mb-4">
//                 <div className="card-body">
//                   <h3 className="card-title mb-3">Create Event</h3>
//                   <PostForm />
//                 </div>
//               </div>
//             </div>
//           </div>
//         </div>
//       </main>
//     </>
//   );
// }

import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import PostList from "@/components/PostList.js";
import PostForm from "@/components/PostForm.js";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Expanding Financial Security @ Prudential</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className="container">
          <h1 className="text-center mt-5 mb-4">Expanding Financial Security @ Prudential</h1>

        
  <div className={`position-relative mb-4 ${styles["hero-image"]} ${styles["fade-in"]}`}>
            <img
              src="https://www.prudential.com/content/dam/community-engagement/Community-Engagement.jpg"
              className="img-fluid rounded shadow-lg"
              alt="Community Engagement"
            />
            <div className={styles["hero-text"]}>
              <p>Prudential believes in making a societal impact by expanding financial security.</p>
            </div>
          </div>
          {/* Post List */}
          <div className="row">
            <div className="col-lg-8">
              <div className="mb-4">
                <PostList />
              </div>
            </div>

            {/* Post Form */}
            <div className="col-lg-4">
              <div className="card shadow-sm mb-4">
                <div className="card-body">
                  <h3 className="card-title mb-3">Need Volunteers?</h3>
                  <PostForm />
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}


