import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import PostList from "@/components/PostList.js";
import PostForm from "@/components/PostForm.js";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Volunteer With Pru</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      <h1> Volunteer With Pru</h1>

      <PostList />
      <div className="form-area">
            <PostForm />
      </div>
      

      </main>
    </>
  );
}
